### ISSUE TITLE
Issue on page /tutorials/W1D2_StateoftheClimateOceanandAtmosphereReanalysis/W1D2_Tutorial6.ipynb

### ISSUE THREAD

**Issue by pratik-bhandari** [ClimateMatchAcademy/course-content#212] opened 2023-07-18 17:30 UTC
On the third code block [[here](https://comptools.climatematch.io/tutorials/W1D2_StateoftheClimateOceanandAtmosphereReanalysis/student/W1D2_Tutorial6.html#section-1-vertical-distribution-of-heat-within-the-ocean)], the comment is incomplete.

It just says: `# plot a zonal mean slice of this data. we take a mean just in longitudes by dividing the dA coordinate by the`.

**Comment by jlpearso** [comment] 2023-07-19 04:47
Duplicate of issue #211 . Closing this one and will address other issue.

**Closed by jlpearso** 2023-07-19 04:47 UTC
